---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/books":
    post:
      summary: Creates a book
      tags:
      - Books
      parameters:
      - name: book
        in: body
        schema:
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            author:
              type: string
            publisher:
              type: string
            genre:
              type: string
            edition:
              type: number
            release_date:
              type: string
          required:
          - title
          - author
          - genre
          - publisher
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
  "/api/v1/books/{id}":
    get:
      summary: Retrieves a book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: book found
          schema:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              description:
                type: string
              author:
                type: string
              publisher:
                type: string
              genre:
                type: string
              edition:
                type: number
                x-nullable: true
              release_date:
                type: string
                x-nullable: true
              created_at:
                type: timestamps
              updated_at:
                type: timestamps
            required:
            - id
            - title
            - author
            - genre
            - publisher
        '404':
          description: book not found
